version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: A123456
      MYSQL_DATABASE: throme
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      # 挂载 Windows 目录（注意：要使用 / 斜杠 或 \ 转义）
      - ../mysqldata/config:/etc/mysql/conf.d
      - ../mysqldata/data:/var/lib/mysql
      - ../mysqldata/init:/docker-entrypoint-initdb.d
    restart: always  